version: '3.8'

services:
  mysqldb:
    image: mysql:8.3.0
    restart: always
    container_name: DBRoyIntisoft
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
      - MYSQL_DATABASE=inventory_it
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql

